source 'https://github.com/CocoaPods/Specs.git'

#use_frameworks!

#platform :ios, '12.0'

target 'TuChannel_Example' do
  pod 'TuChannel', :path => '../'

  target 'TuChannel_Tests' do
    inherit! :search_paths

    
  end
end
